### ISSUE TITLE
Register a new user via REST API

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/membership#17]
While registering the user, put him in status `WAITING_MAIL_CONFIRMATION` and ask user to validate his mail address (by sending him an email with link to click).

While registering, make sure that email is unique.

After confirming, put status to `ACTIVATED`.

**Comment by 0pdd** [comment]
@baudoliver7 2 puzzles [#19](https://github.com/Minlessika/membership/issues/19), [#20](https://github.com/Minlessika/membership/issues/20) are still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#19](https://github.com/Minlessika/membership/issues/19) is still not solved; solved: [#20](https://github.com/Minlessika/membership/issues/20).
